[package]
name = "cargo-ebuild"
version = "0.4.1-dev"
authors = ["Doug Goldstein <cardoe@cardoe.com>"]
license = "MIT/Apache-2.0"
edition = "2018"
repository = "https://github.com/cardoe/cargo-ebuild"
homepage = "https://github.com/cardoe/cargo-ebuild"
documentation = "https://github.com/cardoe/cargo-ebuild"
readme = "README.md"
keywords = ["cargo-subcommand", "ebuild", "gentoo"]
categories = ["command-line-utilities"]
description = """
Generates an ebuild for a package using the in-tree eclasses.
"""

[[bin]]
name = "cargo-ebuild"
path = "src/main.rs"

[lib]
name = "cargo_ebuild"
path = "src/lib.rs"

[dependencies]
anyhow = "^1"
cargo-lock = "^7.0"
cargo_metadata = "^0.14"
itertools = "^0.10"
rustsec = "0.24.2"
structopt = "^0.3"
serde = { version = "1.0", features = ["derive"] }
time = "^0.3"

[dependencies.phf]
version = "0.10"
features = ["macros"]

[dependencies.tera]
version = "1"
default-features = false
